DROP TABLE ITEMVENDA;
DROP TABLE VENDA;
DROP TABLE PRODUTO;
DROP TABLE SUBCATEGORIA;
DROP TABLE CATEGORIA;
DROP TABLE CLIENTE;
DROP TABLE VENDEDOR;
DROP TABLE HISTORICODEPARTAMENTO;
DROP TABLE DEPARTAMENTO;
DROP TABLE EMPREGADO;
DROP TABLE TELEFONE;
DROP TABLE PESSOA;
DROP TABLE ENDERECO;
DROP TABLE SYS_LOG;

DROP MATERIALIZED VIEW LOG ON PRODUTO;
DROP MATERIALIZED VIEW LOG ON SUBCATEGORIA;
DROP MATERIALIZED VIEW LOG ON VENDA;

COMMIT;
